  export const INPUTSTORE=' INPUTSTORE'
  export const  EDITOR='EDITOR'
  export const MINIMIZE="MINIMIZE"
  export const EXPANDPREVIEW="EXPANDPREVIEW"
  export const MINIMIZEPREVIEW="MINIMIZEPREVIEW"

